version: "3.9"
services:
  restaurante-cardapio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delivery-restaurante-cardapio
    restart: unless-stopped
    ports:
      - "9521:9521"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
